# Generated by Django 6.0.2 on 2026-03-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledocument',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='priority',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
