# Generated by Django 6.0.2 on 2026-05-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profiledocument_is_active_profiledocument_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='session_name',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores route, mode, model used, retrieval info, UI action, etc.'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Visitor IP address for analytics/security tracking.', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='referrer',
            field=models.TextField(blank=True, help_text='Page or source that referred the visitor.', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser/device information.', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='visitor_id',
            field=models.CharField(blank=True, db_index=True, help_text='Anonymous visitor identifier stored in frontend localStorage/cookie.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='citations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
