# Generated by Django 6.0.2 on 2026-05-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='visitor_email',
            field=models.EmailField(blank=True, db_index=True, help_text='Visitor email collected before starting chatbot conversation.', max_length=254, null=True),
        ),
    ]
