# Generated by Django 6.0.2 on 2026-05-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contactmessage_projectrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='admin_note',
            field=models.TextField(blank=True, default='', help_text='Optional internal admin note about this session.'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='admin_status',
            field=models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='open', help_text='Admin review workflow status for this chat session.', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='When the admin closed or archived this session.', null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the admin marked this session as reviewed.', null=True),
        ),
    ]
