# Generated by Django 6.0.2 on 2026-05-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_chatsession_admin_note_chatsession_admin_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_prefix', models.CharField(default='Hi, I am', help_text='Small text before the main name/title.', max_length=100)),
                ('main_title', models.CharField(default='Samah Fujo', help_text="Main hero title, usually the portfolio owner's name.", max_length=150)),
                ('subtitle', models.CharField(blank=True, default='Senior Python/Django Engineer with 5+ years of experience', help_text='Short professional headline.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Main hero paragraph shown under the title.')),
                ('primary_button_text', models.CharField(default='Download CV', max_length=80)),
                ('primary_button_url', models.CharField(blank=True, default='/cv.pdf', help_text='URL or file path for the primary button.', max_length=255)),
                ('secondary_button_text', models.CharField(default='Start Project', max_length=80)),
                ('secondary_button_url', models.CharField(blank=True, default='#contact', help_text='URL or section anchor for the secondary button.', max_length=255)),
                ('hero_image', models.ImageField(blank=True, help_text='Main portrait or hero image.', null=True, upload_to='hero/')),
                ('background_image', models.ImageField(blank=True, help_text='Optional background image or brush effect.', null=True, upload_to='hero/backgrounds/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one active hero section should be used on the public website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
                'ordering': ['-updated_at'],
            },
        ),
    ]
