# Generated by Django 6.0.2 on 2026-05-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_herosection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_image_dark',
            field=models.ImageField(blank=True, help_text='Hero image used in dark mode.', null=True, upload_to='hero/images/dark/'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_image_light',
            field=models.ImageField(blank=True, help_text='Hero image used in light mode.', null=True, upload_to='hero/images/light/'),
        ),
    ]
