# Generated by Django 6.0.2 on 2026-05-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_herosection_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={},
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='main_title',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='title_prefix',
        ),
        migrations.AddField(
            model_name='herosection',
            name='eyebrow_text',
            field=models.CharField(blank=True, default='Hi, I am', max_length=100),
        ),
        migrations.AddField(
            model_name='herosection',
            name='full_name',
            field=models.CharField(blank=True, default='Samah Fujo', max_length=150),
        ),
        migrations.AddField(
            model_name='herosection',
            name='headline',
            field=models.CharField(blank=True, default='Senior Python/Django Engineer', max_length=255),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='hero_image_dark',
            field=models.ImageField(blank=True, null=True, upload_to='hero/images/dark/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='hero_image_light',
            field=models.ImageField(blank=True, null=True, upload_to='hero/images/light/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='primary_button_text',
            field=models.CharField(blank=True, default='Download CV', max_length=80),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='primary_button_url',
            field=models.CharField(blank=True, default='/assets/files/Samah-Fujo-CV.pdf', max_length=255),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='secondary_button_text',
            field=models.CharField(blank=True, default='Start Project', max_length=80),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='secondary_button_url',
            field=models.CharField(blank=True, default='modal:start-project', max_length=255),
        ),
    ]
