# Generated by Django 6.0.2 on 2026-05-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_herosection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, default='About me', help_text='Main section heading displayed on the left side.', max_length=120)),
                ('terminal_label', models.CharField(blank=True, default='samah.dev', help_text='Small label shown in the terminal/browser window header.', max_length=120)),
                ('welcome_title', models.CharField(blank=True, default='✨ Welcome', help_text='Welcome heading inside the terminal content.', max_length=120)),
                ('description', models.TextField(blank=True, default='', help_text='Main About Me paragraph shown inside the terminal window.')),
                ('is_active', models.BooleanField(default=True, help_text='Only the active About section will be displayed on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
                'ordering': ['-updated_at'],
            },
        ),
    ]
