# Generated by Django 6.0.2 on 2026-05-20 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(blank=True, default='Expertise', help_text='Small badge text shown above the section title.', max_length=80)),
                ('title_line_1', models.CharField(blank=True, default='Skills &', help_text='First line of the Skills section title.', max_length=120)),
                ('title_line_2', models.CharField(blank=True, default='Capabilities.', help_text='Second line of the Skills section title.', max_length=120)),
                ('description', models.TextField(blank=True, default='A comprehensive toolkit built through years of hands-on experience and continuous learning.', help_text='Short description shown on the right side of the section header.')),
                ('is_active', models.BooleanField(default=True, help_text='Only the active Skills section will be displayed on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Section',
                'verbose_name_plural': 'Skill Sections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, default='CodeBracketIcon', help_text='Icon name used by AppIcon, for example CodeBracketIcon.', max_length=100)),
                ('title', models.CharField(help_text='Skill card title.', max_length=150)),
                ('description', models.TextField(blank=True, default='', help_text='Short skill description.')),
                ('experience', models.CharField(blank=True, default='1+ Years', help_text='Experience label, for example 5+ Years.', max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls display order. Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active skill items are shown on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(help_text='The Skills section this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.skillsection')),
            ],
            options={
                'verbose_name': 'Skill Item',
                'verbose_name_plural': 'Skill Items',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
