# Generated by Django 6.0.2 on 2026-05-21 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_skillsection_skillitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillitem',
            options={'ordering': ['category', 'sort_order', 'created_at'], 'verbose_name': 'Skill Item', 'verbose_name_plural': 'Skill Items'},
        ),
        migrations.RemoveField(
            model_name='skillitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skillitem',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='skillitem',
            name='title',
        ),
        migrations.AddField(
            model_name='skillitem',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('AI / LLM', 'AI / LLM'), ('Database', 'Database'), ('DevOps', 'DevOps'), ('Languages', 'Languages'), ('UI', 'UI')], default='Frontend', max_length=50),
        ),
        migrations.AddField(
            model_name='skillitem',
            name='label',
            field=models.CharField(default='skill', help_text='Skill name shown on the website, for example React.', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillitem',
            name='level',
            field=models.PositiveIntegerField(default=7, help_text='Skill level from 1 to 10.'),
        ),
        migrations.AddField(
            model_name='skillitem',
            name='summary_heading',
            field=models.CharField(blank=True, default='Practical technical capability', max_length=180),
        ),
        migrations.AddField(
            model_name='skillitem',
            name='summary_points',
            field=models.JSONField(blank=True, default=list, help_text='List of points explaining why this skill matters.'),
        ),
        migrations.AddField(
            model_name='skillitem',
            name='summary_text',
            field=models.TextField(blank=True, default='This skill supports my real project delivery and contributes to building complete, production-oriented solutions.'),
        ),
        migrations.AlterField(
            model_name='skillitem',
            name='icon',
            field=models.CharField(default='react', help_text='TechIcon name, for example react, nextjs, docker, python.', max_length=100),
        ),
        migrations.AlterField(
            model_name='skillitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='skillitem',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.skillsection'),
        ),
        migrations.AlterField(
            model_name='skillitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
