# Generated by Django 6.0.2 on 2026-05-21 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_skillitem_options_remove_skillitem_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Projects', help_text='Main title shown above the Projects section.', max_length=120)),
                ('description', models.TextField(blank=True, default='Selected work across AI, automation, analytics, and full-stack product development', help_text='Short description shown below the Projects section title.')),
                ('is_active', models.BooleanField(default=True, help_text='Only the active Projects section will be displayed on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Section',
                'verbose_name_plural': 'Project Sections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title shown on the website.', max_length=180)),
                ('slug', models.SlugField(blank=True, help_text='Unique project slug used internally and later for project detail pages.', max_length=220, unique=True)),
                ('short_description', models.TextField(blank=True, default='', help_text='Short text shown on project cards.')),
                ('description', models.TextField(blank=True, default='', help_text='Full project description shown in the selected project detail card.')),
                ('thumbnail_image', models.ImageField(blank=True, help_text='Small image used in project cards.', null=True, upload_to='projects/thumbnails/')),
                ('hero_image', models.ImageField(blank=True, help_text='Large image used in the selected project hero preview.', null=True, upload_to='projects/hero/')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Image alt text for accessibility.', max_length=180)),
                ('category', models.CharField(blank=True, default='AI Project', help_text='Project category badge, for example AI Dashboard or LLM Application.', max_length=100)),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text="List of technologies, for example ['Django', 'React', 'PostgreSQL'].")),
                ('demo_link', models.URLField(blank=True, default='', help_text='Optional demo/video link.', max_length=600)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls display order. Lower numbers appear first.')),
                ('is_featured', models.BooleanField(default=True, help_text='Featured projects are shown in the main Projects section.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active projects are shown on the public website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(help_text='The Projects section this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.projectsection')),
            ],
            options={
                'verbose_name': 'Project Item',
                'verbose_name_plural': 'Project Items',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
