# Generated by Django 6.0.2 on 2026-05-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_projectsection_projectitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectitem',
            name='demo_link',
        ),
    ]
