# Generated by Django 6.0.2 on 2026-05-22 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_projectitem_demo_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Certificates', help_text='Main title shown above the Certificates section.', max_length=120)),
                ('description', models.TextField(blank=True, default='Professional certifications and achievements', help_text='Short description shown below the Certificates section title.')),
                ('is_active', models.BooleanField(default=True, help_text='Only the active Certificates section will be displayed on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Section',
                'verbose_name_plural': 'Certificate Sections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Full certificate title.', max_length=220)),
                ('mobile_title', models.CharField(blank=True, default='', help_text='Short title shown in mobile thumbnails and previous/next labels.', max_length=80)),
                ('slug', models.SlugField(blank=True, help_text='Unique certificate slug used internally.', max_length=240, unique=True)),
                ('issuer', models.CharField(blank=True, default='', help_text='Certificate issuer, for example Udemy, IBM via Coursera, Coursiv.', max_length=160)),
                ('issue_date', models.CharField(blank=True, default='', help_text='Display date, for example Jan 25, 2025 or 5 February 2026.', max_length=80)),
                ('certificate_image', models.ImageField(blank=True, help_text='Certificate image used in carousel and preview modal.', null=True, upload_to='certificates/images/')),
                ('certificate_file', models.FileField(blank=True, help_text='Optional PDF certificate file.', null=True, upload_to='certificates/files/')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Image alt text for accessibility.', max_length=220)),
                ('skills', models.JSONField(blank=True, default=list, help_text="List of skills, for example ['React', 'Django', 'REST API'].")),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls display order. Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active certificates are shown on the public website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(help_text='The Certificates section this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.certificatesection')),
            ],
            options={
                'verbose_name': 'Certificate Item',
                'verbose_name_plural': 'Certificate Items',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
