# Generated by Django 6.0.2 on 2026-05-22 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_certificatesection_certificateitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Research', help_text='Main title shown above the Research section.', max_length=120)),
                ('description', models.TextField(blank=True, default='Published papers, articles, and academic contributions', help_text='Short description shown below the Research section title.')),
                ('is_active', models.BooleanField(default=True, help_text='Only the active Research section will be displayed on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Research Section',
                'verbose_name_plural': 'Research Sections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Research paper/article title.', max_length=500)),
                ('slug', models.SlugField(blank=True, help_text='Unique slug used internally.', max_length=520, unique=True)),
                ('research_type', models.CharField(default='Article', help_text='Type badge shown on the card, for example Article or Conference Paper.', max_length=120)),
                ('publish_date', models.CharField(blank=True, default='', help_text='Display date, for example November 2022.', max_length=120)),
                ('reads', models.CharField(blank=True, default='0', help_text='Display reads count, for example 404.', max_length=50)),
                ('citations', models.CharField(blank=True, default='0', help_text='Display citations count, for example 2.', max_length=50)),
                ('authors', models.JSONField(blank=True, default=list, help_text="List of authors, for example ['Moaiad Khder', 'Samah Fujo'].")),
                ('primary_action', models.CharField(blank=True, default='Read More', help_text='Main action button text.', max_length=80)),
                ('primary_action_href', models.URLField(blank=True, default='', help_text='Main action link, for example ResearchGate URL.', max_length=1000)),
                ('share_href', models.URLField(blank=True, default='', help_text='Share link. Usually same as the ResearchGate/publication URL.', max_length=1000)),
                ('image', models.ImageField(blank=True, help_text='Optional uploaded image for the research card.', null=True, upload_to='research/images/')),
                ('external_image_url', models.URLField(blank=True, default='', help_text='Optional external image URL, for example Unsplash image.', max_length=1000)),
                ('alt_text', models.CharField(blank=True, default='', help_text='Image alt text for accessibility.', max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Controls display order. Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active research items are shown on the public website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(help_text='The Research section this item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.researchsection')),
            ],
            options={
                'verbose_name': 'Research Item',
                'verbose_name_plural': 'Research Items',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
