# Generated by Django 6.0.2 on 2026-06-01 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_researchsection_researchitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchStatsRefreshLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('no_change', 'No Change'), ('partial', 'Partial'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='failed', max_length=30)),
                ('old_reads', models.CharField(blank=True, default='', max_length=50)),
                ('new_reads', models.CharField(blank=True, default='', max_length=50)),
                ('old_citations', models.CharField(blank=True, default='', max_length=50)),
                ('new_citations', models.CharField(blank=True, default='', max_length=50)),
                ('reads_fetched', models.BooleanField(default=False)),
                ('citations_fetched', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('source_url', models.URLField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_refresh_logs', to='core.researchitem')),
            ],
            options={
                'verbose_name': 'Research Stats Refresh Log',
                'verbose_name_plural': 'Research Stats Refresh Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
