# Generated by Django 6.0.2 on 2026-06-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_researchstatsrefreshlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchstatsrefreshlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('no_change', 'No Change'), ('partial', 'Partial'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('manual', 'Manual Update')], default='failed', max_length=30),
        ),
    ]
