# Generated by Django 6.0.2 on 2026-06-01 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_researchstatsrefreshlog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_title', models.CharField(blank=True, default='Follow me', max_length=120)),
                ('copyright_name', models.CharField(blank=True, default='Samah Fujo', max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Sections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FooterContactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=255)),
                ('href', models.CharField(blank=True, default='', help_text='Example: mailto:s.fujo@hotmail.com or tel:+971527929218', max_length=1000)),
                ('icon_key', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('location', 'Location')], default='email', max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_items', to='core.footersection')),
            ],
            options={
                'verbose_name': 'Footer Contact Item',
                'verbose_name_plural': 'Footer Contact Items',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('icon_key', models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('tiktok', 'TikTok')], default='linkedin', max_length=40)),
                ('url', models.URLField(max_length=1000)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='core.footersection')),
            ],
            options={
                'verbose_name': 'Footer Social Link',
                'verbose_name_plural': 'Footer Social Links',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
