# Generated by Django 6.0.2 on 2026-06-02 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_footersection_footercontactitem_footersociallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentProcessingLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(help_text='Example: upload_started, extraction_completed, embedding_failed.', max_length=120)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional structured log metadata.')),
            ],
            options={
                'verbose_name': 'Document Processing Log',
                'verbose_name_plural': 'Document Processing Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentQualityCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_name', models.CharField(max_length=120)),
                ('check_status', models.CharField(choices=[('passed', 'Passed'), ('warning', 'Warning'), ('failed', 'Failed')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict, help_text='Optional structured details about the check result.')),
            ],
            options={
                'verbose_name': 'Document Quality Check',
                'verbose_name_plural': 'Document Quality Checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileDocumentVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='profile_documents/versions/')),
                ('raw_text_snapshot', models.TextField(blank=True, default='')),
                ('status_snapshot', models.CharField(blank=True, default='', max_length=30)),
                ('quality_score_snapshot', models.FloatField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Profile Document Version',
                'verbose_name_plural': 'Profile Document Versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='profiledocument',
            options={'ordering': ['priority', '-updated_at'], 'verbose_name': 'Profile Document', 'verbose_name_plural': 'Profile Documents'},
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='character_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of characters in the chunk.'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_dimension',
            field=models.PositiveIntegerField(default=1024),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_model',
            field=models.CharField(blank=True, default='', help_text='Name of the embedding model used.', max_length=120),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='has_embedding',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Only active chunks are used by chatbot retrieval.'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='quality_issues',
            field=models.JSONField(blank=True, default=list, help_text='List of detected chunk issues.'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='quality_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='quality_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('warning', 'Warning'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='token_count',
            field=models.PositiveIntegerField(default=0, help_text='Approximate number of tokens or words in the chunk.'),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='admin_notes',
            field=models.TextField(blank=True, default='', help_text='Internal admin notes about this document.'),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='chunk_quality_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='embedding_quality_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='extracted_text_preview',
            field=models.TextField(blank=True, default='', help_text='Short preview of extracted text for admin list/detail display.'),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='extraction_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Used to detect duplicate uploaded documents.', max_length=128),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='Uploaded file size in bytes.'),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='True only after admin approval.'),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='is_available_for_chatbot',
            field=models.BooleanField(default=False, help_text='Final safety flag used by chatbot retrieval.'),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='mime_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='overall_quality_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='processing_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Stores extraction/chunking/embedding metadata.'),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='quality_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('warning', 'Warning'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Required when document is rejected.'),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='validation_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Stores document validation result summary.'),
        ),
        migrations.AlterField(
            model_name='profiledocument',
            name='document_type',
            field=models.CharField(blank=True, help_text='Example: CV, certificate, project summary, recommendation letter.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profiledocument',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only active and approved documents can be used by chatbot.'),
        ),
        migrations.AlterField(
            model_name='profiledocument',
            name='priority',
            field=models.PositiveSmallIntegerField(default=5, help_text='1 = highest priority, 10 = lowest priority.'),
        ),
        migrations.AlterField(
            model_name='profiledocument',
            name='raw_text',
            field=models.TextField(blank=True, help_text='Full extracted text from the uploaded document.', null=True),
        ),
        migrations.AlterField(
            model_name='profiledocument',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('extracted', 'Extracted'), ('extraction_failed', 'Extraction Failed'), ('validating', 'Validating'), ('validation_failed', 'Validation Failed'), ('validation_warning', 'Validation Warning'), ('chunking', 'Chunking'), ('chunked', 'Chunked'), ('chunking_failed', 'Chunking Failed'), ('embedding', 'Generating Embeddings'), ('embedded', 'Embedded'), ('embedding_failed', 'Embedding Failed'), ('ready_for_review', 'Ready for Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='uploaded', max_length=30),
        ),
        migrations.AlterField(
            model_name='profiledocument',
            name='tags',
            field=models.JSONField(blank=True, help_text="List of tags, for example ['cv', 'python', 'django'].", null=True),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='core_docume_documen_d1a0b0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['has_embedding'], name='core_docume_has_emb_5b925f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['quality_status'], name='core_docume_quality_a9e495_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['is_active'], name='core_docume_is_acti_1a4044_idx'),
        ),
        migrations.AddIndex(
            model_name='profiledocument',
            index=models.Index(fields=['status'], name='core_profil_status_8dea04_idx'),
        ),
        migrations.AddIndex(
            model_name='profiledocument',
            index=models.Index(fields=['quality_status'], name='core_profil_quality_eed869_idx'),
        ),
        migrations.AddIndex(
            model_name='profiledocument',
            index=models.Index(fields=['is_active', 'is_approved', 'is_available_for_chatbot'], name='core_profil_is_acti_4f078b_idx'),
        ),
        migrations.AddIndex(
            model_name='profiledocument',
            index=models.Index(fields=['file_hash'], name='core_profil_file_ha_8eb2f1_idx'),
        ),
        migrations.AddIndex(
            model_name='profiledocument',
            index=models.Index(fields=['document_type'], name='core_profil_documen_816cfd_idx'),
        ),
        migrations.AddField(
            model_name='documentprocessinglog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='core.profiledocument'),
        ),
        migrations.AddField(
            model_name='documentqualitycheck',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='core.profiledocument'),
        ),
        migrations.AddField(
            model_name='profiledocumentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.profiledocument'),
        ),
        migrations.AddIndex(
            model_name='documentprocessinglog',
            index=models.Index(fields=['document'], name='core_docume_documen_99a55f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentprocessinglog',
            index=models.Index(fields=['level'], name='core_docume_level_04ae30_idx'),
        ),
        migrations.AddIndex(
            model_name='documentprocessinglog',
            index=models.Index(fields=['step'], name='core_docume_step_be12f6_idx'),
        ),
        migrations.AddIndex(
            model_name='documentqualitycheck',
            index=models.Index(fields=['document'], name='core_docume_documen_f960a8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentqualitycheck',
            index=models.Index(fields=['check_status'], name='core_docume_check_s_6f7b60_idx'),
        ),
        migrations.AddIndex(
            model_name='documentqualitycheck',
            index=models.Index(fields=['severity'], name='core_docume_severit_59bce0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='profiledocumentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
