# Generated by Django 6.0.2 on 2026-06-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_documentprocessinglog_documentqualitycheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledocument',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text='Whether an admin has reviewed the extracted text, chunks, embeddings, and quality checks.'),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='review_notes',
            field=models.TextField(blank=True, default='', help_text='Admin notes added during document review.'),
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the document was reviewed by an admin.', null=True),
        ),
    ]
