# Generated by Django 6.0.6 on 2026-07-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_websitevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitevisit',
            name='browser_name',
            field=models.CharField(blank=True, db_index=True, default='other', help_text='Classified browser name such as chrome, safari, firefox, edge, opera, or other.', max_length=50),
        ),
        migrations.AddField(
            model_name='websitevisit',
            name='device_type',
            field=models.CharField(blank=True, db_index=True, default='unknown', help_text='Classified device type: desktop, mobile, tablet, or unknown.', max_length=50),
        ),
        migrations.AddField(
            model_name='websitevisit',
            name='event_name',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Specific event name such as hero_start_project_click, chat_opened, or linkedin_click.', max_length=100),
        ),
        migrations.AddField(
            model_name='websitevisit',
            name='source_type',
            field=models.CharField(blank=True, db_index=True, default='direct', help_text='Classified source type: direct, search, social, internal, or referral.', max_length=50),
        ),
        migrations.AddField(
            model_name='websitevisit',
            name='utm_campaign',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Marketing campaign name.', max_length=150),
        ),
        migrations.AddField(
            model_name='websitevisit',
            name='utm_content',
            field=models.CharField(blank=True, default='', help_text='Optional campaign content or variant.', max_length=150),
        ),
        migrations.AddField(
            model_name='websitevisit',
            name='utm_medium',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Marketing medium such as social, referral, qr, or email.', max_length=150),
        ),
        migrations.AddField(
            model_name='websitevisit',
            name='utm_source',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Marketing source such as linkedin, instagram, github, or cv.', max_length=150),
        ),
        migrations.AddField(
            model_name='websitevisit',
            name='utm_term',
            field=models.CharField(blank=True, default='', help_text='Optional paid/search term.', max_length=150),
        ),
        migrations.AlterField(
            model_name='websitevisit',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('cta_click', 'CTA Click'), ('custom', 'Custom'), ('engagement', 'Engagement'), ('frontend_error', 'Frontend Error'), ('chatbot_error', 'Chatbot Error'), ('form_error', 'Form Error')], db_index=True, default='page_view', max_length=20),
        ),
    ]
