[
"tell me about your certficate",
"what experiance do you have in django",
"do you no react",
"what projcts have you done",
"tell me about your ai skilss",
"have you worked with machien learning",
"what is your backgroud in python",
"do you have experiance in next js",
"what kind of dashbords did you build",
"have you used postgress before",

"tell me about your python skills",
"what do you know about django",
"do you know drf",
"what frontend technologies do you use",
"do you work with next js",
"have you used react in production",
"what databases have you worked with",
"do you know mongodb",
"have you used docker and nginx",
"do you have experience with api security",

"what experience do you have in AI",
"have you worked with llms",
"tell me about your nlp background",
"have you built rag systems",
"what do you know about transformers",
"have you used hugging face",
"do you work with prompt engineering",
"have you used ollama before",
"do you know langchain",
"have you worked with gemini api",

"tell me about your spend analysis project",
"what is the live smart electricity dashboard",
"tell me about your payroll auditing system",
"what is your ai property search chatbot",
"which project used bert or roberta",
"what projects have you done in procurement",
"tell me about your dashboard projects",
"what project involved oracle database",
"which project used django and react",
"what project used ai for classification",

"what certifications do you have",
"do you have any ai certificate",
"tell me about your master of chatgpt certificate",
"what is the master of claude certificate",
"do you have a react and django certificate",
"what courses have you completed",
"have you studied ai agents",
"what learning achievements do you have",
"tell me about your technical certifications",
"what did you learn from your certificates",

"what is your current role",
"are you an ai engineer",
"do you work as a full stack developer",
"what kind of backend work do you do",
"have you led teams before",
"what industries have you worked in",
"tell me about your professional experience",
"what kind of clients have you worked with",
"have you built enterprise systems",
"do you have leadership experience",

"ما هي خبرتك في django",
"هل لديك خبرة في الذكاء الاصطناعي",
"tell me about خبرتك في python",
"ما هي المشاريع التي عملت عليها",
"هل عندك شهادات في AI",
"خبرتك في react و next js",
"هل استخدمت ollama من قبل",
"ما هو مشروع spend analysis",
"حدثني عن مهاراتك التقنية",
"هل لديك خبرة في OCR",

"tell me about yourself",
"what can you do",
"what are your strongest skills",
"what kind of solutions do you build",
"what makes your profile strong",
"what do you specialize in",
"what should i know about your background",
"what is your technical focus",
"what have you built recently",
"what is your main expertise",

"which projects combine django and ai",
"which of your projects used dashboards and machine learning",
"what work have you done with procurement classification",
"which skills are related to backend and ai together",
"what certificates support your ai profile",
"what technologies do you use in production systems",
"which project involved ocr and document understanding",
"what evidence is there that you worked with llms",
"what technologies appear across multiple projects",
"which experiences show leadership and technical depth",

"",
"   ",
"python",
"ai",
"certificate",
"project",
"???",
"tell me more",
"same as before",
"do you"
]