"""
Django settings for workportfolio project.
Generated by 'django-admin startproject' using Django 6.0.2.
"""

from corsheaders.defaults import default_headers
import environ
from pathlib import Path
import os
from decouple import config
from dotenv import load_dotenv
load_dotenv()




BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default: str = "") -> list[str]:
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


ADMIN_API_KEY = config("ADMIN_API_KEY")
SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = env_bool("DEBUG", False)

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "dev-only-insecure-secret-key-change-me"
    else:
        raise ValueError("SECRET_KEY must be set when DEBUG is False.")


MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MAX_DOCUMENT_UPLOAD_SIZE = int(
    os.getenv("MAX_DOCUMENT_UPLOAD_SIZE", str(5 * 1024 * 1024)))
ALLOWED_DOCUMENT_EXTENSIONS = {".pdf", ".docx", ".txt"}

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "127.0.0.1,localhost,testserver")
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", "")


RESEND_API_KEY = config("RESEND_API_KEY", default="")
CONTACT_TO_EMAIL = config(
    "CONTACT_TO_EMAIL", default="s.fujo@hotmail.com")  # your receiving email
CONTACT_FROM_EMAIL = config(
    "CONTACT_FROM_EMAIL", default="onboarding@resend.dev")
CONTACT_BCC_EMAIL = config("CONTACT_BCC_EMAIL", default="")

# Later change CONTACT_FROM_EMAIL to your verified domain sender, e.g. no-reply@samah.ai

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core',


]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

REST_FRAMEWORK = {
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "10/min",
        "contact": os.getenv("CONTACT_THROTTLE_RATE", "5/min"),
        "chat": os.getenv("CHAT_THROTTLE_RATE", "20/min"),
        "upload": os.getenv("UPLOAD_THROTTLE_RATE", "10/hour"),
        "admin_api": "1000/minute",
    },
}

CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000,http://localhost:4028,http://127.0.0.1:4028",
)

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-api-key",
]

CORS_ALLOW_CREDENTIALS = False

ROOT_URLCONF = 'workportfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'workportfolio.wsgi.application'


# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True


SESSION_COOKIE_SECURE = env_bool("SESSION_COOKIE_SECURE", not DEBUG)
CSRF_COOKIE_SECURE = env_bool("CSRF_COOKIE_SECURE", not DEBUG)
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", False)

SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    False,
)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", False)

if env_bool("USE_X_FORWARDED_PROTO", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMBEDDING_PROVIDER = os.getenv("EMBEDDING_PROVIDER", "jina")
JINA_API_KEY = os.getenv("JINA_API_KEY")
EMBEDDING_DIM = int(os.getenv("EMBEDDING_DIM", "1024"))


# ============================================================
# gemini settings
# ============================================================
GEMINI_REWRITE_API_KEY = env("GEMINI_REWRITE_API_KEY", default="")
GEMINI_GROUNDED_API_KEY = env("GEMINI_GROUNDED_API_KEY", default="")

DEEPSEEK_API_KEY = env("DEEPSEEK_API_KEY", default="")
DEEPSEEK_BASE_URL = env(
    "DEEPSEEK_BASE_URL",
    default="https://api.deepseek.com/chat/completions",
)
# LLM_HTTP_TIMEOUT = env.int("LLM_HTTP_TIMEOUT", default=60)

GROUNDED_PRIMARY_MODEL = env(
    "GROUNDED_PRIMARY_MODEL",
    default="gemini-2.5-flash-lite",
)
GROUNDED_SECONDARY_MODEL = env(
    "GROUNDED_SECONDARY_MODEL",
    default="deepseek-chat",
)
GROUNDED_GEMINI_MAX_RETRIES = env.int(
    "GROUNDED_GEMINI_MAX_RETRIES",
    default=3,
)


ASSISTED_ANSWER_MODEL_CHAIN = ["deepseek-chat", "gemini-2.5-flash-lite"]
# ============================================================
# Reranker settings
# ============================================================
RERANK_MIN_SCORE = float(os.getenv("RERANK_MIN_SCORE", "0.20"))
RERANK_CANDIDATE_K = int(os.getenv("RERANK_CANDIDATE_K", "40"))
RERANK_TOP_N = int(os.getenv("RERANK_TOP_N", "8"))


# ============================================================
# Admin dashboard settings
# ============================================================
# ADMIN_API_KEY = os.getenv("ADMIN_API_KEY")
ADMIN_API_KEY = config("ADMIN_API_KEY", default="")



# **Credentials:DB Postgres**

# * Host: `127.0.0.1`
# * Port: `5432`
# * User: `postgres`
# * Password: `postgres`